# Generated by Django 2.0.3 on 2018-06-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20180526_2012'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('test_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestLog')),
            ],
            options={
                'verbose_name': 'Лог вопросов',
                'verbose_name_plural': 'Логи вопросов',
            },
        ),
    ]
