# Generated by Django 2.0.3 on 2018-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='klass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='points_amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество баллов'),
        ),
    ]
