# Generated by Django 2.0.3 on 2018-03-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('estimate_method', models.CharField(choices=[('default', 'Стандартный'), ('many_answers', 'Множество ответов')], max_length=50, verbose_name='Метод оценки')),
                ('duration', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
