# Generated by Django 2.0.3 on 2018-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180317_1141'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course_id',
        ),
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
