# Generated by Django 2.0.3 on 2018-03-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20180317_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
