# Generated by Django 2.0.3 on 2018-03-26 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0003_auto_20180317_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Назначенный тест', max_length=255, verbose_name='Заголовок')),
                ('duration', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность')),
                ('datetime_start', models.DateTimeField(verbose_name='Начало теста')),
                ('datetime_end', models.DateTimeField(verbose_name='Окончание теста')),
            ],
            options={
                'verbose_name': 'Назначенный тест',
                'verbose_name_plural': 'Назначенные тесты',
            },
        ),
        migrations.CreateModel(
            name='AvailableTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Доступный тест', max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Доступный тест',
                'verbose_name_plural': 'Доступные тесты',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.AddField(
            model_name='availabletest',
            name='tests',
            field=models.ManyToManyField(to='tests.Test', verbose_name='Тесты'),
        ),
        migrations.AddField(
            model_name='availabletest',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='appointedtest',
            name='tests',
            field=models.ManyToManyField(to='tests.Test', verbose_name='Тесты'),
        ),
        migrations.AddField(
            model_name='appointedtest',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
