# Generated by Django 2.0.3 on 2018-04-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_auto_20180326_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_uid', models.UUIDField(default=uuid.uuid4, verbose_name='Код теста')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Начало теста')),
                ('datetime_completed', models.DateTimeField(blank=True, null=True, verbose_name='Начало теста')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Результат')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История тестов',
                'verbose_name_plural': 'Истории тестов',
            },
        ),
        migrations.AddField(
            model_name='appointedtest',
            name='test_size',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Количество вопросов'),
        ),
        migrations.AddField(
            model_name='availabletest',
            name='test_size',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Количество вопросов'),
        ),
    ]
