# Generated by Django 2.0.3 on 2018-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20180407_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletest',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='datetime_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание теста'),
        ),
    ]
