# Generated by Django 2.0.3 on 2018-05-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20180512_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testlog',
            options={'permissions': (('can_read_stats', 'Может просмотривать статистику'),), 'verbose_name': 'История тестов', 'verbose_name_plural': 'Истории тестов'},
        ),
    ]
