# Generated by Django 2.0.3 on 2018-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_testklassdepence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='estimate_method',
            field=models.CharField(choices=[('default', 'Стандартный'), ('many_answers', 'Множество ответов'), ('klass_depence', 'Классовый подбор')], max_length=50, verbose_name='Метод оценки'),
        ),
    ]
